atheme/atheme

modules/hostserv/request.c

Prevents users from requesting the vhost that's already active on their account (or nick, if `request_per_nick` is active)

HostServ REQUEST: Ignore request if vhost already active

---

include/hooktypes.in
modules/groupserv/drop.c
modules/groupserv/register.c
modules/hostserv/offer.c

GroupServ/HostServ: Remove group-specific offered vhosts when group dropped

---

include/crypto.h
libathemecore/auth.c
libathemecore/crypto.c
modules/crypto/pbkdf2v2.c

some concerns about parameter upgrades over time
Also tidy up some styling and add a comment about salt length.
NOTE: Other modules need to be investigated for possible integration
into this scheme

Implement a within-module parameter upgrade system to satisfy

---

dist/atheme.conf.example

Since you didn't like the SaslServ part, I'll just resubmit this with only the +e included.

+e added to chanserv{} templates and founder_flags

---

modules/saslserv/main.c

As requested by @tomaw, this calls `bad_password` on users failing to identify to an account via SASL to help spot brute force attacks on passwords. Given that this might be a little confusing to users and doesn't include much info about the actual source, this can be toggled by a config option.

saslserv: optionally call bad_password on SASL authentication failure

---

help/default/nickserv/list
modules/nickserv/vacation.c

* adds new NickServ LIST criterion `VACATION`
* adds the `NOPASSWORD` criterion to the LIST helpfile
* adds conditionals to helpfile, to ensure that criteria defined by unloaded modules do not appear

NickServ LIST things

---

configure
configure.ac
include/sysconf.h.in
include/tools.h
libathemecore/Makefile
libathemecore/arc4random.c
libathemecore/chacha_private.h
libathemecore/explicit_bzero.c

This imports the ChaCha20-based arc4random.c from OpenSSH-portable.

Update internal arc4random to a more recent version

---

libathemecore/arc4random.c
libathemecore/chacha_private.h
libathemecore/cidr.c
libathemecore/match.c

I left one instance of `u_long` in `connection.c` due to it being windows specific as it's included in winsock.

Move away from BSD data types

---

help/default/nickserv/cert

change following the addition of CLEAR by @siniStar7boy in  https://github.com/atheme/atheme/commit/aaea9febcfcda1c7abaae149ca54bd04b296bd56#diff-2a84376e28acf689ea567432c7ca9fdf

Add mention of CLEAR command

---

NEWS.md

NEWS: update for 7.2.7

---

modules/crypto/ircservices.c

Hello, this change is only aesthetic, it's a suggestion to avoid the use of conditional directives that break statements i think that kind of concern improve the code maintainability do you agree?
Also, this pull request is based on #470  changes and conversation.

Avoiding conditional directives that split up parts of statements

---

help/default/nickserv/setpass

fixed typo

---

help/default/cservice/recover

Users get confused by recover relatively often ...

add reference to '/msg chanserv help OP'

---

modules/nickserv/identify.c

Notify users who just identified, if verification is incomplete. Untested edit. Copied from modules/nickserv/info.c.

Notify users if verification is incomplete

---

include/tools.h
modules/gameserv/dice.c
modules/gameserv/gamecalc.c
modules/gameserv/lottery.c

gameserv: Use arc4random_uniform() everywhere

---

include/atheme/entity-validation.h
include/atheme/entity.h
include/atheme/structures.h
libathemecore/account.c
libathemecore/entity.c
modules/chanserv/sync.c
modules/chanserv/why.c
modules/exttarget/chanacs.c
modules/exttarget/channel.c
modules/exttarget/oper.c
modules/exttarget/registered.c
modules/exttarget/server.c
modules/groupserv/main/groupserv.c
modules/groupserv/main/groupserv_main.h
modules/groupserv/main/main.c
modules/groupserv/main/validation.c

Poking @aaronmdjones since this might affect some of the stuff you've been working on, plus for an overall review if possible.
This will help with #676, which is my primary motivation for getting this in for 7.3.0.

entity validation: avoid indirection via chanacs

---

doc/perl/Atheme/Hooks.pod
include/atheme/hook.h
include/atheme/hooktypes.in
modules/chanserv/akick.c
modules/chanserv/main.c
modules/chanserv/set_entrymsg.c
modules/chanserv/set_restricted.c
modules/chanserv/set_url.c
modules/chanserv/sync.c
modules/groupserv/main/hooks.c

This cleans up a lot of code duplication and some related cleanup. It'll also simplify the upcoming AKICK changes which are blocking 7.3 right now.

Moving chanuser sync to hooks

---

modules/nickserv/info.c

The existing approach rounds the elapsed time down to weeks, which does reduce the resolution of last seen times to a week over one observation. Unfortunately, if we're allowed multiple observations, we can zero in on the time the low-resolution clock ticks over.
The solution used here is to reduce the resolution of the last-seen time itself. Since the time is not changing, this happens the same way each time, and subsequent observations reveal no information. This is not perfect on its own: it discloses high-resolution information about users who were last seen at the beginning of the current Atheme week, since they couldn't have been last seen in the future. We deal with this by representing both 0- and 1-week differences as "less than two weeks ago".
Finally, this is of limited value …

nickserv/info: Make private last-seen times more private

---

libathemecore/ctcp-common.c

noopcanon -> strcasecanon; case insensitive CTCP

---

modules/nickserv/enforce.c

This addresses a race condition where the user is "banned" on a channel
because all unregistered users are banned, preventing them from changing
their nick.
---
This is an alternate take on #711. I maintain that this is the wrong fix, but it's your project, so here you go.

NickServ REGAIN: log in before changing nick

---

include/atheme/account.h
include/atheme/privs.h
libathemecore/flags.c
modules/nickserv/identify.c
modules/nickserv/info.c
modules/nickserv/loginnolimit.c
modules/operserv/specs.c
modules/saslserv/main.c

as per #652. most of this was stolen from how regnolimit works.
n.b. I do not speak very good C

implement NS LOGINNOLIMIT <nick> ON|OFF

---

modules/chanserv/close.c
modules/chanserv/drop.c
modules/chanserv/ftransfer.c
modules/chanserv/hold.c
modules/chanserv/mark.c
modules/groupserv/acsnolimit.c
modules/groupserv/drop.c
modules/groupserv/regnolimit.c
modules/nickserv/drop.c
modules/nickserv/freeze.c
modules/nickserv/hold.c
modules/nickserv/loginnolimit.c
modules/nickserv/mark.c
modules/nickserv/register.c
modules/nickserv/regnolimit.c
modules/nickserv/resetpass.c
modules/nickserv/restrict.c
modules/nickserv/return.c
modules/nickserv/sendpass.c
modules/nickserv/sendpass_user.c
modules/nickserv/vhost.c
modules/operserv/ignore.c
modules/operserv/jupe.c
modules/operserv/readonly.c

some were bold, some were not, and we decided that bold is the way to go! so this bolds the things that were not bolded.

boldify soper name in wallops

---

dist/atheme.conf.example
include/atheme/global.h
libathemecore/conf.c
libathemecore/phandler.c
modules/protocol/charybdis.c
modules/protocol/chatircd1.1.c
modules/protocol/inspircd.c
modules/protocol/unreal.c
modules/protocol/unreal4.c

See solanum-ircd/solanum#150 and the commit message for details and rationale.

Add match_masks_through_vhost option for Solanum

---

modules/gameserv/happyfarm.c

Comment typo: nore ➡️ node

---

modules/hostserv/offer.c

I think this is a more complete approach to #804, and handles the case where there's a single offer but it's restricted by group. Not properly tested because I don't have a local ircd any more.

Allow HS TAKE without params if there's only one HS OFFER (#2)

---

include/atheme/tools.h
libathemecore/function.c
modules/chanserv/topic.c

gib de topic reject reason more verbose explanation

---

INSTALL

People who set up their first IRC network will read this documentation,
it seems unnecessary to shame them for... not knowing how to setup
and IRC network.

INSTALL: Remove unnessarily agressive remark

---

dist/atheme.conf.example
doc/IRCD

Document Insp 3 support

---

include/atheme/account.h
libathemecore/account.c
libathemecore/services.c
modules/nickserv/Makefile
modules/nickserv/enforce.c
modules/nickserv/identify.c
modules/saslserv/main.c

services.c/enforce.c: honor no login limit flag

---

modules/hostserv/main.c
modules/nickserv/vhost.c

seems like a good idea in general, seems like it won't have adverse effects, hopefully solves https://github.com/atheme/atheme-contrib-modules/issues/21

increase importance of vhost-related user_identified hooks

---

include/atheme/privs.h
libathemecore/account.c
libathemecore/conf.c
libathemecore/privs.c
modules/nickserv/group.c
modules/nickserv/set_accountname.c

and also allow config uid sopers to change accountname

allow config file sopers to be specified by ?UID

---

doc/FAQ

And drop numbers, so sections can be inserted in the middle without renumbering

doc/FAQ: Reformat like INSTALL

---

modules/chanserv/list.c

I'm certain there's going to be something about how I chose to pass the information back from `process_parvarray()` that isn't right, but it works!
closes #801

don't just ignore invalid CS LIST criteria/parameters

---

modules/nickserv/identify.c
modules/saslserv/main.c

a slightly better and more general solution to https://github.com/atheme/atheme-contrib-modules/pull/60

don't call hook_user_login_check for redundant logins

---

modules/protocol/inspircd.c

Fixes the issue reported by blackbeard on IRC.

Fix parsing remote SERVER messages from InspIRCd.

---

.github/workflows/ci.yml
.github/workflows/periodic-coverity-scan.yml
README.md
include/atheme/match.h
libathemecore/match.c
m4/atheme-libtest-pcre.m4

Motivation cf. https://fedoraproject.org/wiki/Changes/PcreDeprecation (not just Fedora, openSUSE has started removal processes too).

PCRE2 support
