atheme/atheme

modules/protocol/charybdis.c
modules/protocol/inspircd.c
modules/protocol/unreal.c

In certain circumstances, the mask string passed into is_extban can contain space(s) and currently there is no validation in any protocol module implementing extbans that the input mask indeed contains no spaces. An example circumstance is ChanServ's BAN command.
The following command will cause ChanServ to set a ban on the first mask due to how the MODE command works, but fail to add the ban to Atheme itself due to the mask being the full rest of the string as opposed to just a single word.
`/msg ChanServ BAN #channel $a:mask1 $a:mask2`
This patch adds a simple strchr check for the space character to each extban check, fixing the issue outlined above.

protocol: Fail extban check if mask contains space

---

.mailmap
help/default/groupserv/flags
modules/groupserv/drop.c
modules/groupserv/flags.c
modules/groupserv/invite.c
modules/groupserv/join.c
modules/groupserv/main/groupserv.c

This pull request eliminates issues arising from hardcoded parsing of flags in the GroupServ flags parser. The GroupServ FLAGS help text is updated to reflect the now functional GroupServ flag +A (allows viewing of group access list). Additionally, issues with flags +* are fixed and now the behaviour is more consistent with that of ChanServ.
More details are available in the individual commit messages.

Fix GroupServ issues

---

NEWS.md
dist/atheme.conf.example
modules/crypto/Makefile
modules/crypto/pbkdf2v2.c

This version embeds the PRF and iteration count into the crypt()-like
strings it generates, meaning that you can change these defaults in
the module at a later date without invalidating all of your current
hashes. You can also extend it with new PRFs for this reason.
The usage of sscanf(3) in this module is consistent with ISO C89 and
there is a comment in the source file reminding people not to change
the format strings carelessly.

Implement better PBKDF2 hashing for passwords

---

dist/atheme.conf.example
include/sasl.h
modules/saslserv/main.c

Change the SASL `bad_password` description to `Unknown user on <server> (via SASL)`. If `hide_server_names` is set the description is `Unknown user (via SASL)`.

saslserv: make bad_password description more user-friendly

---

modules/scripting/perl/api/make_perl_hooks.pl

This pull request firstly fixes the lack of ordering of the code output in `perl_hooks.c` to allow the second patch and future patches to be verified for correctness by `diff`ing the generated file with the file generated by the unmodified code. Details on why this first patch is necessary can be found in its commit message.
The second patch makes the Perl API forward compatible with any new hooks added to Atheme and is outlined in more detail in its commit message.

Make Perl API forward compatible

---

include/flags.h
libathemecore/cidr.c
libathemecore/flags.c
modules/groupserv/groupserv.h
modules/groupserv/main/groupserv.c
modules/groupserv/main/groupserv_main.h

* Replace all remaining uses of `struct gflags` with `gflags_t` for consistency
* Declare a buffer in `cidr.c` as unsigned to suppress a type warning when compiled with clang

Stylistic edits

---

modules/nickserv/ghost.c

Fixes the following issues:
* The checks for frozen-ness and the nopassword flag were bypassed for unregistered targets (also fixes an assert fail from `metadata_find` when this occurred)
* If a password was provided, it was ignored for unregistered targets

Fix some problems with unregistered target nicks in NickServ GHOST

---

configure
configure.ac
include/sysconf.h.in

More or less same deal as in https://github.com/charybdis-ircd/charybdis/commit/35472d0f1f52c31213cf9f96b4d80da91d27a865

automake: Fix typo in compiler flag

---

modules/protocol/nefarious.c

Fixes issue where Atheme is unable to enforce & send glines to other servers on Nefarous. (Credit to tacocat)
Fixes issue where unregistered users uncloaked IP address is exposed when banning with services on Nefarious.

Protocol patches for Nefarious

---

modules/protocol/unreal.c
modules/protocol/unreal4.c

UnrealIRCd SVSNICK is server only (at least on 3.2.10.6 and 4.0.3.1). When NickServ is used as a source, the following error is sent by the uplink and the SVSNICK command silently fails.
```
[2016-07-11 23:01:51] <- :NickServ NOTICE GL4 :GL has been released.
[2016-07-11 23:01:51] NickServ GL/AAAAAAAAB:GL4!gl@localhost[localhost] RELEASE: GL!GLolol@escape.the.dreamland.ca
[2016-07-11 23:01:51] -> :unreal.midnight.vpn 487 NickServ :SVSNICK is a server only command
```
edit: fix typo in title & commit (-mode)

protocols/unreal*: fix wrong source for SVSNICK

---

libathemecore/function.c

This is a purely cosmetic change to differentiate between automated emails from services and messages sent from the IRC network entity itself.

libathemecore: mark emails as from "%netname% Network Services"

---

modules/chanserv/main.c

We can still deop external services through OS MODE, but we shouldn't automatically deop them, that's none of our business.

MC_SECURE: do not deop services

---

libathemecore/memory.c

As the branch name implies, just something I noticed thats been there for ~10 years due to a copy/paste error :p

memory: Fix copyright header

---

email/default/register
email/default/setemail
email/default/setpass

The leading whitespace is barely visible in many email clients and was often cause for sending the message directly to the channel for clients that do not interpret " /command" as a command. This was most notable for qwebirc.
This change was not tested to work (I don't have a good test environment), but from discussion in `#atheme` it appears that this should be sufficient.

email templates: Fix leading whitespace

---

po/Makefile

Fix the following parts of POT creation:
- Update target file variable to use $(PACKAGE_NAME), fixing a problem
where the POT file would be written as '.pot' instead of 'atheme.pot'.
- Update call to xgettext to supply it with the following information:
- Define a package name via $(PACKAGE_NAME)
- Define a package version via $(PACKAGE_VERSION)
- Define the copyright holder as "Atheme"
- Define <https://github.com/atheme/atheme/issues> as report address
for msgid bugs

po/Makefile: fix POT creation

---

dist/atheme.conf.example
modules/crypto/pbkdf2v2.c

This series of commits better highlights the use of PBKDF2 for hashing passwords and makes certain parameters configurable at runtime (with defaults documented).
This pull request needs review as I have not written config-parsing code in Atheme before. I have tested it locally.

Improve the PBKDF2v2 module

---

libathemecore/services.c

Introduced by the merge of https://github.com/XthemeOrg/Xtheme/commit/fdebfad3f3023c67b6b24e8c62307d5140ae9ea7 but not used in this function.

services.c: remove unused pointer

---

modules/saslserv/main.c

```
==9829== 136 bytes in 1 blocks are definitely lost in loss record 440 of 447
==9829==    at 0x4C2CA40: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9829==    by 0x52C109A: smalloc (memory.c:35)
==9829==    by 0xC487B92: sasl_sourceinfo_create (main.c:274)
==9829==    by 0xC4887F0: login_user (main.c:605)
==9829==    by 0xC4887F0: sasl_packet.constprop.6 (main.c:467)
==9829==    by 0xC488E6B: sasl_input (main.c:347)
==9829==    by 0x52BE5AD: hook_call_event (hook.c:192)
==9829==    by 0x6FDED40: m_encap.part.15 (ts6-generic.c:1304)
==9829==    by 0x71E3CDA: irc_parse (parse.c:176)
==9829==    by 0x52C31FD: irc_recvq_handler (packet.c:55)
==9829==    by 0x52BB010: recvq_put (datastream.c:266)
==9829==    by 0x5081762: mowgli_epoll_eventloop_select …
```

saslserv/main: free sasl_sourceinfo_t after use

---

help/default/alis/list

I think the help should say "- a channel name pattern does not start with a wildcard or a #, or" instead of "- a channel name pattern starts with a wildcard or a #, or"
Relevant code
https://github.com/atheme/atheme/blob/master/modules/alis/main.c#L135
Brought up by ccat at #freenode today

Fix a logical blunder

---

modules/nickserv/register.c

The password should not be sent back to the client for security reasons.
An attacker could potentially read the message from the screen until the
message has been cleared (e.g. when registering in public) or the
message could be logged by the client.
In the latter case, this might not even be known to the user.
As for the former case, many applications obscure the password to
prevent such situations from happening. Since the password is not really
necessary in this case, we can also leave it out.
Typos that go unnoticed during registration can be worked around by
using SENDPASS for now, in the future it might be worth to add a special
VERIFY case to have the user enter the password twice.
Closes atheme/atheme#577 ("When registering the response contains the
password as plain text")

nickserv/register: Remove password from registration confirmation

---

include/abirev.h
include/sasl.h
modules/protocol/inspircd.c
modules/protocol/nefarious.c
modules/protocol/ts6-generic.c
modules/protocol/unreal.c
modules/protocol/unreal4.c
modules/saslserv/main.c

This can be used in future to restrict the authentication mechanisms
that plaintext clients are allowed to perform (for example, to
prevent password disclosure to passive observers by preventing
SASL PLAIN).
c.f. https://github.com/charybdis-ircd/charybdis/commit/754c1edf2e9c

SASL: Use a parameter vector to allow arbitrary number of S2S arguments

---

include/servers.h

On UID-less networks such as ngIRCd, defining the numeric option will cause WHOIS responses to break, as they send from the defined SID instead of the server name. (Other commands are not affected though, so this causes a very subtle breakage)
Before:
```
[2017-07-12 07:02:00] -> :james WHOIS chanserv :chanserv
[2017-07-12 07:02:00] <- :0SV 311 james ChanServ ChanServ services.int * :Channel Services
[2017-07-12 07:02:00] <- :0SV 312 james ChanServ services.midnight.int :Atheme IRC Services
[2017-07-12 07:02:00] <- :0SV 313 james ChanServ :is a Network Service
[2017-07-12 07:02:00] <- :0SV 318 james chanserv :End of WHOIS
```
After:
```
[2017-07-12 07:09:51] -> :james WHOIS chanserv :chanserv
[2017-07-12 07:09:51] <- :services.midnight.int 311 james ChanServ ChanServ services.int * …
```

Ignore the serverinfo:numeric setting on UID-less networks

---

modules/protocol/unreal4.c

We added support for SASL v3.2 in UnrealIRCd which requires services to send the saslmechlist. I took a look at how you do it with other IRCd's and made a patch.

Advertise SASL mechanisms to UnrealIRCd servers.

---

libathemecore/function.c
modules/saslserv/scram-sha.c

With this, I can successfully authenticate using both gsasl and Pidgin (cyrus-sasl) as clients.
One remaining issue is that the mechanism isn't re-registered on `/os modreload saslserv/scram-sha`; I have to additionally `/os rehash` to make it work again.

SCRAM-SHA-1 bugfixes

---

modules/chanserv/clear_flags.c

This restriction is useless. Additionally, users might find this
behavior unintuitive.
Closes atheme/atheme#605 (""CLEAR FLAGS" does not need to check if a
registered channel exists")

chanserv/clear_flags: do not check whether or not the channel is empty

---

include/account.h
include/hooktypes.in
include/services.h
libathemecore/account.c
libathemecore/services.c
modules/nickserv/enforce.c
modules/nickserv/freeze.c
modules/nickserv/identify.c
modules/nickserv/logout.c
modules/nickserv/return.c
modules/nickserv/set_accountname.c

* Add a user_can_logout(si, u) hook that can prevent a user from logging out
In a few dubious cases where it would be incorrect/impossible to deny the operation, the target user is killed instead (as if on P10).
* Add a user_can_rename(si, mu, mn) hook

Add a couple login-related hooks

---

modules/operserv/modlist.c

Exposing the module list will not negatively impact network operations.
It will provide a small amount of additional transparency to users, but
cannot expose modifications to default modules that might make them more
malicious.

operserv/modlist: expose list of loaded modules to everyone

---

modules/nickserv/enforce.c

We try to hold the nick and rename its current occupier to GuestXXXXX. The hold step makes sense (to prevent someone taking the nick between the two renames) only if it comes before the first rename.
Additionally, setting UF_DOENFORCE on the nick we're about to rename to doesn't make any sense, so remove that.

nickserv/enforce: fix renaming sequence in REGAIN

---

modules/nickserv/info.c

**HostServ/VHOSTNICK** applies per-nick vhosts using an alternative metadata format `private:userhost:<nick>`. Currently very few, if any, modules within other services built to process vhosts will show per-nick vhosts due to this.
This patch updates **NickServ/INFO** to correctly display all virtual hosts attached to an account, including both the account-based host and all nick-based hosts.

Updated nickserv/info to show vhostnick vhosts

---

help/default/nickserv/release

People are regularly confused when a single use of RELEASE is not sufficient to retrieve their nickname. This change explains that and suggests a second release.

Explain that sometimes RELEASE needs doing twice

---

modules/nickserv/verify.c

As far as I know, there's no information leak here, since it's public information that an account has not been confirmed.

nickserv: allow unidentified VERIFY REGISTER

---

modules/crypto/argon2.c

If libargon2 isn't available, then CRYPTO_MODULE_NAME wasn't being defined for the SIMPLE_DECLARE_MODULE_V1() at the end, so I moved it outside the ifdef.

modules/crypto/argon2: fix compilation without libargon2

---

help/default/nickserv/identify
modules/nickserv/main.c

Many users are only ever exposed to the one-argument variant, and require human assistance to get out of situations that could have been resolved easily. For example, a user matching a `+q $~a` may find themselves stuck on an alternate nick.
Attempt to mitigate this problem by making two-argument IDENTIFY more prominent in help and nags.

nickserv: Prefer advertising two-argument IDENTIFY

---

dist/atheme.conf.example
include/atheme/global.h
libathemecore/conf.c
libathemecore/ptasks.c

as per #728 and the decision made in #730

add config option to hide oper status in remote whois (hide_opers)

---

modules/nickserv/return.c

per #737
if:
- user is not set HIDEMAIL and
- HIDEMAIL in defuflags and
- new email does not equal old email
then force HIDEMAIL on the user

RETURN to a different address should HIDEMAIL if in defuflags

---

dist/atheme.conf.example
include/atheme/services.h
modules/chanserv/count.c
modules/chanserv/flags.c
modules/chanserv/main.c

This essentially allows networks to enable PUBACL even if they can't make akicks public (e.g. networks like freenode that already make ACLs public but exclude akicks from the public listing, so exposing akicks isn't an option without breaking users' existing assumptions about them being private).
Tested, but there's likely to be some edge cases I haven't thought of.

chanserv: allow hiding AKICK entries from public ACLs

---

modules/chanserv/close.c

my proposed solution for #743, stolen from cs/akick.c, still sets the closed channel modes but announces that it isn't kicking you because you're oper/immune.
I did consider instead only kicking users that joined when the channel is already closed, because anyone that can join through `+b *!*@*` should probably be allowed to, but that means you need to do join/kick before you can get in safely, and it's likely a bit vulnerable to timing attacks.

use try_kick() instead of kick() for channels that have been CS CLOSEd

---

dist/atheme.conf.example
help/default/infoserv/move
help/default/infoserv/omove
modules/infoserv/main.c

Fixes #597, which inspired this PR to allow reordering entries and add an option to display just the entries without their setter and timestamp information. It ended up including a few other improvements as well.

Infoserv improvements

---

dist/atheme.conf.example
modules/nickserv/listownmail.c

closes #742.
stole modular setting from `pwquality_warn_only`. I'm not sure I like how visually complicated the `if` is now. pls be gentle

add an option to disable email canon for LISTOWNMAIL comparisons

---

help/default/cservice/list
modules/chanserv/list.c

here's a first attempt at addressing #760. The code seems like a bit of a mess as it's nontrivial to handle channel modes in a generalized way.
There's probably some issues I've overlooked and some optimizations to be made, especially around extmode handling, but it compiles and doesn't crash in the simplest test cases at least

chanserv/list: allow filtering by MLOCK

---

help/default/nickserv/set_accountname
help/default/nickserv/set_enforce
help/default/nickserv/set_pubkey
help/default/nickserv/setpass

For consistenty with other entries.
Adds examples to set_accountname, set_enforce, set_pubkey, and setpass.

Add examples to NickServ help entries.

---

dist/atheme.motd.example
libathemecore/ptasks.c

libathemecore/ptasks.c: STATS:T: make nonsensitive data available
The statistics for `server`, `user`, and `chan` can already be obtained via the `LUSERS` command on IRC, so it does not make sense for services to prevent accessing these by requiring services privileges.
Furthermore, the number of registered accounts, nicknames, and channels should also not be considered sensitive data. The Atheme project does not condone hiding such basic and non-sensitive data from network users.
Finally, put missing `mynicks` count in default MOTD file.

libathemecore/ptasks.c: STATS:T: make nonsensitive data available

---

libathemecore/module.c
modules/operserv/modmanager.c

These are technically two separate issues that I ended up noticing for similar reasons, both causing a use-after-free in code related to module handling because they did not account for the consequences of unloading a module.

Module unloading use-after-free fixes

---

modules/nickserv/verify.c

Currently you can verify an email address change on an unconfirmed account, but it won't confirm the account even though you've just proved that you own its current email address. Everyone I've spoken to about this thinks it's a bug, so here's a fix.
I've also changed the log message to identify the target of the verify, rather than repeating the name of the requestor; morally that should be its own PR, but it would have had a conflict with this one.

Make VERIFY EMAILCHG confirm the account if necessary

---

INSTALL

It didn't really make sense as configuration isn't part of the compilation.
Additionally, not everyone installs Atheme by compiling it themselves,
or they may not have the file at hand while reading this document
(eg. reading the documentation before actually doing it)

Explain configuration outside the "Compiling" section

---

modules/nickserv/group.c

this brings consistency with the wallop from FDROP per modules/nickserv/drop.c L157:
https://github.com/atheme/atheme/blob/d7af86f8b6706ae3866ccff4648c7615775c4ee0/modules/nickserv/drop.c#L157

Bolden oper name in fungroup wallop

---

libathemecore/atheme.c

Avoids an issue where a DB module dependency loads a service which then doesn't get configured properly.

atheme_main: rehash if necessary after DB load

---

dist/atheme.conf.example
include/atheme/account.h
include/atheme/global.h
libathemecore/account.c
libathemecore/conf.c
modules/backend/corestorage.c
modules/backend/flatfile.c
modules/nickserv/cert.c

this check was obviously meant to exist, given
https://github.com/atheme/atheme/blob/1eb6ce571015db4729ec2ce7177949f534c6f633/modules/nickserv/cert.c#L148-L154
the hardcoded `16` is a placeholder for a better value, maybe a setting?

implement certfp list max check

---

modules/nickserv/info.c

I think I'd like to extend this to other data too

simplify NS INFO timestamp logic, indicate auspex being used

---

modules/protocol/ircd-seven.c

This was already defined in the charybdis protocol module but not in ircd-seven, so define it there too.

Support +T (CMODE_NONOTICE) in ircd-seven

---

help/default/cservice/akick

+e was added in 7.2 to exempt users from akick.

help/cservice/akick: correct flag for exempt

---

modules/nickserv/multimark.c

(apologies for changing some stuff to `const` while i was in the neighbourhood)

log account name, rather than provided target, in multimark

---

include/atheme/protocol/solanum.h
modules/protocol/solanum.c

would've felt wrong to put this in the charybdis headers given the mode is new since the fork

give solanum its own protocol headers, add CMODE_MODREG for regmsg

---

include/atheme/hook.h
include/atheme/hooktypes.in
modules/nickserv/cert.c

this is to support a module that will warn users when they add a certificate fingerprint that doesn't look like what we're expecting, i.e.:
```
<jess> cert add f10e2821bbbea527ea02200352313bc059445190
-NickServ- Warning: fingerprint of unexpected length. Expected hash algorithm: SHA512.
-NickServ- Added fingerprint f10e2821bbbea527ea02200352313bc059445190 to your fingerprint list.
```

add hooks for adding and removing a certificate fingerprint

---

modules/nickserv/drop.c

corollary to atheme/atheme@214b0efbbde3ab55f7bbfd93d6cc7d2a5d181df6

allow config sopers who are specified by EID to drop their account

---

configure
include/atheme/sysconf.h.in
m4/atheme-check-build-requirements.m4
modules/proxyscan/dnsbl.c

This does make the codebase now depend upon `inet_pton(3)`, which is pretty much universally available.

proxyscan/dnsbl: add IPv6 support

---

modules/protocol/unreal4.c

This lets the package name be declared in a way where unrealircd's new admin panel can display

This lets Unreal know about the package and version

---

dist/atheme.conf.example

this throttle mechanism is documented in 2 places; `modules/misc/login_throttling.c` and in this file. the comments explain `replenish` differently; i've checked the math and i've checked in practice, and `modules/misc/login_throttling.c` is correct.
example with `burst` set to 1 and `replenish` set to 2:
```
02:34:47 <jess> identify jess a
02:34:47 -NickServ(NickServ@atheme.vpn.lolnerd.net)- Invalid password for jess.
02:34:47 <jess> identify jess a
02:34:47 -NickServ(NickServ@atheme.vpn.lolnerd.net)- You cannot identify to jess because the server configuration disallows it.
02:34:48 <jess> identify jess a
02:34:48 -NickServ(NickServ@atheme.vpn.lolnerd.net)- You cannot identify to jess because the server configuration disallows it.
02:34:48 <jess> identify jess a
02:34:48 …
```

rectify throttling config example, as `replenish` is seconds-per-token

---

NEWS.md
dist/atheme.conf.example
doc/PRIVILEGES
include/atheme/privs.h
libathemecore/entity.c
modules/groupserv/register.c
modules/nickserv/group.c
modules/nickserv/regnolimit.c
modules/operserv/specs.c

the priv `user:regnolimit` currently refers to yourself. if you have this priv, you can register as much of anything as you want.
the nickserv command `REGNOLIMIT` is used at run-time to change whether another user can register as many channels as they'd like.
we wanted to change the priv that the nickserv command requires (it currently requires `general:admin`), but `user:regnolimit` was already being used for the first usecase, so i've decided to change the first usecase to be `user:exceedlimits`

'user:regnolimit' -> 'user:exceedlimits', use :regnolimit for NS command

---

modules/protocol/ts6-generic.c

it may be better to only send this extra parameter to servers whose `CAPAB`/`GCAP` have indicated they support it. thoughts?

include FNC_REGAIN/FNC_FORCE in ts6-generic's RSFNC

---

dist/atheme.conf.example
modules/operserv/Makefile
modules/operserv/joinrate.c

I thought this was better as a first-party module than to put it in contrib. I have reworked it to adhere to the 7.3 type system and conventions, and add module reload support such that no data loss will occur.
This still needs to be thoroughly tested.

modules/operserv/: add a channel join rate monitoring module

---

modules/protocol/unreal4.c

When parsing the UID message from UnrealIRCd, the real IP of the user is not being correctly detected.
According to UnrealIRCd documentation (5+), the UID line should be as follows.
UID nickname hopcount timestamp username hostname uid servicestamp umodes virthost cloakedhost ip :gecos
This appears to be caused due to an additional check that requires parc to be both 11 and 12 to successfully extract the IP.

modules/protocol/unreal4: Adjust UID parsing to correctly parse IP

---

help/default/contrib/trace

The help string for the TRACE criteria "NICKAGE" used to suggest that NICKAGE looks at connection age.
This was inaccurate because NICKAGE actually tests based on nick age, as nickname changes update the user timestamp.

help/default/contrib/trace: use correct help message for NICKAGE

---

dist/atheme.conf.example
doc/IRCD
modules/protocol/inspircd.c

This drops support for v2 (which has been eol for years now) and adds support for v4 (via the v3 compatibility layer).
I'd appreciate help testing this. I have tested it myself but I might have missed some stuff.
Closes #904.

Update InspIRCd protocol module to use the 1205 (v3) protocol

---

modules/transport/rfc1459/parse.c

This fixes parsing some messages on InspIRCd and other IRCds that send message tags.

transport/rfc1459: Skip IRCv3 message tags if they exist.

---

modules/protocol/inspircd.c

1. Topic changes were not handled correctly when sent by a user outside of the initial burst.
2. When logging "all" to !snotices a SNONOTICE message would be sent during a connection phase when it is not allowed.
3. Some obsolete code in m_ping was allowing the burst to end but not allowing the uplink to be considered synchronised.
4. When an operator on a non-directly connected server joined the channel using `/OJOIN` their channel prefix mode was not being mapped to a prefix character correctly.
5. CBANs should be added through ADDLINE not through the client command.
6. Account identifiers should be synchronised with the IRC server if public. This is used by the server for tracking users if the account is renamed.

Fix various minor issues with the InspIRCd protocol module

---

email/fr/memo
email/fr/register
email/fr/sendpass
email/fr/setemail
email/fr/setpass

Add french translation for email templates.
As discussed with `amdj` on IRC, there would still be some work to do to make services use this translated templates, but at least it's here now.

[template/email] add french translation

---

modules/nickserv/info.c

NS INFO, when the target user is Private, would unconditionally use `mn->lastseen` and `mu->lastlogin`. The upshot is that when a session has used a nick/account for a long enough without triggering anything that would cause these values to update (e.g. nick changes, secondary logins), the displayed times would increase.
This would lead to stuff like this (seen in the wild):
```
Last seen  : (about 2 weeks ago)
Last seen  : (hidden) now
User seen  : (about 2 weeks ago)
User seen  : (hidden) now
```
Those times (for the non-auspex lines) should say "less than two weeks ago".
This PR fixes the display without routinely updating the `lastseen` or `lastlogin` times
by moving the `command_success_nodata` call for `hide_info` into the `is online` checks,
and passing `CURRTIME` to …

Fix displayed last/user seen times for logged-in Private users
